# Generated by Django 4.0.4 on 2022-06-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_stock_quantity_alter_stock_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='current_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
