# Generated by Django 4.0.4 on 2022-06-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_stock_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='percentage_change_1Y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='percentage_change_3Y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='percentage_change_YTD',
            field=models.FloatField(default=0.0),
        ),
    ]
