# Generated by Django 4.0.4 on 2022-06-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_stock_date_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='have_sold_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_sold_price',
            field=models.IntegerField(default=0),
        ),
    ]
