# Generated by Django 4.0.4 on 2022-06-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_stock_have_sold_stock_stock_last_sold_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='percentage_change_last_sold',
            field=models.IntegerField(default=0),
        ),
    ]
