# Generated by Django 4.0.4 on 2022-06-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_stock_percentage_change_last_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='908444', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='have_sold_stock',
            field=models.BooleanField(),
        ),
    ]
