# Generated by Django 4.0.4 on 2023-03-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_multipleimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipleimage',
            name='title',
            field=models.CharField(default='sample', max_length=100),
            preserve_default=False,
        ),
    ]
