# Generated by Django 4.0.4 on 2023-03-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_multipleimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipleimage',
            name='title',
        ),
        migrations.AddField(
            model_name='multipleimage',
            name='label',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
