# Generated by Django 4.0.4 on 2023-03-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_multipleimage_images_noiseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noiseimage',
            name='images',
            field=models.FileField(upload_to=''),
        ),
    ]
